### ISSUE TITLE
NodeJS SDK - Gateway class in Fabric-Network fails to connect to a running network 

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#45]
Hello

Firstly, minicab is a wonderful tool and has helped cut development times for us significantly. 

Using Minifab I have setup up a fabric network chain code on the network. However, I cannot connect to the running network using the NodeJS SDK. The entire network, connection profile and wallet directories have been generated by Minifab.  

The problem is that error I get the following error.
```[bash]
2020-08-03T11:57:26.774Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer-1.tdn-1.kasese.penta, url:grpcs://peer-1.tdn-1.kasese.penta:7051, connected:false, connectAttempted:true
2020-08-03T11:57:26.775Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer-1.tdn-1.kasese.penta url:grpcs://peer-1.tdn-1.kasese.penta:7051 timeout:3000
2020-08-03T11:57:26.778Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer-1.tdn-1.kasese.penta due to Error: Failed to connect before the deadline on Endorser- name: peer-1.tdn-1.kasese.penta, url:grpcs://peer-1.tdn-1.kasese.penta:7051, connected:false, connectAttempted:true
    at checkState (/Users/ed/Dropbox/Development/Blockchains/Kasese/penta-kasese-pilot/Platform/Trusted_Data_Layer/Blockchain-Drivers/node_modules/@grpc/grpc-js/build/src/client.js:69:26)
    at Timeout._onTimeout (/Users/ed/Dropbox/Development/Blockchains/Kasese/penta-kasese-pilot/Platform/Trusted_Data_Layer/Blockchain-Drivers/node_modules/@grpc/grpc-js/build/src/channel.js:292:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  connectFailed: true
}

I use the following bash script to set up the network:
```[bash]
#!/bin/bash

CHANNEL=mychannel
DATABASE=couchdb
CHAINCODE_DIR=mychaincode

docker ps

if [ -d './vars' ]; then 
    /bin/rm -fr ./vars
fi

minifab up -o org1.example.penta -s $DATABASE -c $CHANNEL

if [ -d "./vars" ] && [ -d "./vars/chaincode" ]; then 
    cp -R $CHAINCODE_DIR ./vars/chaincode
    cd ./vars/chaincode/mychaincode/node
    /bin/rm -fr package-lock.json node_modules 
    ls -l 
    cd ../../../..
    minifab install -n mychaincode -l node -v 1.0 
    minifab approve -n mychaincode -v 1.0
    minifab commit -n mychaincode -v 1.0 
    minifab discover
fi
```
and the Node JS code is the following and the error seems to occur at the ```gateway.connect``` statement.
```[javascript]
const {Gateway, Wallets} = require('fabric-network');
...
const gatewayOptions = {
        identity : 'admin',
        wallet :   walletPath,
        discovery : {"enabled": true,"asLocalhost": true}
    };

const gateway = new Gateway();
try {
        await gateway.connect( currentProfile, gatewayOptions );
} catch(error) {
        console.log(`${error}`)
}
```
It feels like the docker ports are unpublished but have I may have missed something? Can you help? 
Thanks - Ed

**Comment by litong01** [comment]
how did you setup your fabric network? I think you need to expose the port, simply do this

```
minifab up -e true
```

This way, your various node port will be exposed to outside of the machine running your fabric. then you can connect to various node. If you are running your app on the same machine but not within a container on the same docker network, you would still have issues, in this case, you will also need to use -e flag to expose the port. However, if you run your app inside a container which is also uses the same docker network, you do not need to expose ports.

**Comment by litong01** [comment]
@edkaz by default, the port is not exposed.

**Comment by edkaz** [comment]
Hello
I used ```minifab up -o org1.example.penta -s $DATABASE -c $CHANNEL``` without the ```-e true``` to expose the endpoints. Of course we are running our app/platform outside of the docker network  and now with the ```-e true``` flag set things seem to be working fine. Again thanks for the quick responses and for your help. - Ed
